name: Arduino compile test
on: [push, pull_request]

jobs:
  build-uno:
    name: Adafruit Feather 32u4 board 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0

      - name: Install Adafruit AVR core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr@1.8.3
          arduino-cli core install adafruit:avr@1.4.13
          
      - name: Prepare code and submodules
        run: |
          git submodule init
          git submodule update
          
      - name: Compile script
        run: |
          arduino-cli compile --fqbn=adafruit:avr:feather32u4 src/src.ino
